export const VOCAB_ERRORS = {
  DECK_NOT_FOUND: (identifier: string) => `Deck not found: ${identifier}`,
  DECK_FORBIDDEN: 'You do not have permission to access or modify this deck',
  DECK_PUBLISH_MIN_CARDS: (cardCount: number) =>
    `Cannot publish deck. A minimum of 2 flashcards is required to publish, but this deck has ${cardCount}.`,
  DECK_LIFECYCLE_INVALID_TRANSITION: (from: string, to: string) =>
    `Deck lifecycle transition from ${from} to ${to} is not allowed`,
  DECK_TITLE_REQUIRED: 'Deck title is required and cannot be empty',
  DECK_TITLE_TOO_LONG: 'Deck title cannot exceed 100 characters',
  DECK_OWNER_REQUIRED: 'Deck must belong to an owner',
  DECK_SLUG_EMPTY: 'Slug cannot be empty',
  FLASHCARD_NOT_FOUND: (cardId: string) => `Flashcard not found: ${cardId}`,
  FLASHCARD_DECK_REQUIRED: 'Flashcard must belong to a deck',
  FLASHCARD_TERM_REQUIRED: 'Flashcard term is required and cannot be empty',
  FLASHCARD_TERM_TOO_LONG: 'Flashcard term cannot exceed 255 characters',
  FLASHCARD_DEFINITION_REQUIRED: 'Flashcard definition is required and cannot be empty',
  FLASHCARD_DEFINITION_TOO_LONG: 'Flashcard definition cannot exceed 1000 characters',
  FLASHCARD_EXAMPLE_TOO_LONG: 'Flashcard example cannot exceed 500 characters',
  FLASHCARD_POSITION_NEGATIVE: 'Flashcard position must be non-negative',
  FLASHCARD_ORDER_MUST_BE_EXACT_PERMUTATION:
    'Flashcard order must contain every card in the deck exactly once',
  FLASHCARD_EDITOR_INVALID_SNAPSHOT:
    'Deck editor changes must account for every existing flashcard exactly once',
  VOCAB_PROGRESS_NOT_FOUND: (id: string) => `Vocab progress not found: ${id}`,
  VOCAB_PROGRESS_USER_REQUIRED: 'User ID is required',
  VOCAB_PROGRESS_DECK_REQUIRED: 'Deck ID is required',
  VOCAB_PROGRESS_FLASHCARD_REQUIRED: 'Flashcard ID is required',
  VOCAB_PROGRESS_INVALID_BOX: 'Box number must be between 1 and 5',
  VOCAB_PROGRESS_NEGATIVE_STREAK: 'Correct streak cannot be negative',
  VOCAB_PROGRESS_NEGATIVE_CORRECT_COUNT: 'Correct count cannot be negative',
  VOCAB_PROGRESS_NEGATIVE_INCORRECT_COUNT: 'Incorrect count cannot be negative',
  FLASHCARD_NOT_IN_DECK: (cardId: string, deckId: string) =>
    `Flashcard ${cardId} does not belong to deck ${deckId}`,
  EMPTY_PROGRESS_SUBMISSION: 'Progress results array cannot be empty',
  PROGRESS_RESULTS_REQUIRED: 'Results array cannot be empty',
  PROGRESS_RESULTS_UNIQUE_FLASHCARDS: 'Results must contain unique flashcardId values',
  STUDY_ATTEMPT_SINGLE_ANSWER: 'An attempt must contain exactly one answer',
  PROGRESS_WRITE_CONFLICT: 'Progress changed concurrently. Please submit the review again.',
  STUDY_ATTEMPT_CONFLICT: 'Attempt ID was already used for a different answer',
  IMPORT_RECEIPT_CONFLICT: 'Import ID was already used for a different deck or content',
  IMPORT_WRITE_CONFLICT: 'Deck changed concurrently. Please retry the import.',
  IMPORT_PAYLOAD_TOO_LARGE: 'Import payload exceeds the 4 MiB limit.',
  IMPORT_CARD_LIMIT_EXCEEDED: 'Import cannot contain more than 2000 cards.',
  EXPORT_LIMIT_EXCEEDED: 'This deck is too large for the 2000-card, 4 MiB import backup format.',
  INVALID_PROGRESS_DATA: (reason: string) => `Invalid vocab progress data: ${reason}`,
  PERSONALIZED_STUDY_FILTER_AUTH_REQUIRED: 'Personalized study filters require authentication',
  DECK_EDITOR_FLASHCARDS_REQUIRED: 'Editor save response requires flashcards',
} as const;
