export const IMPORT_MAX_CARDS = 2000;
export const IMPORT_MAX_PAYLOAD_BYTES = 4 * 1024 * 1024;
export const IMPORT_TRANSPORT_HEADROOM_BYTES = 512;
export const DECK_EDITOR_MAX_CARDS = IMPORT_MAX_CARDS;
export const LEARN_SESSION_MAX_CARDS = 500;
