packages:
  - frontend
  - backend

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - "@swc/core"
  - bcrypt
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

ignoredBuiltDependencies:
  - "@scarf/scarf"
