export const PROXY_ERROR_CODES = {
  CSRF_FORBIDDEN: 'CSRF_FORBIDDEN',
  INVALID_PATH: 'INVALID_PATH',
  INVALID_REQUEST_BODY: 'INVALID_REQUEST_BODY',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UPSTREAM_REDIRECT: 'UPSTREAM_REDIRECT',
  UPSTREAM_UNAVAILABLE: 'UPSTREAM_UNAVAILABLE',
  INVALID_REFRESH_RESPONSE: 'INVALID_REFRESH_RESPONSE',
  SESSION_REFRESH_UNAVAILABLE: 'SESSION_REFRESH_UNAVAILABLE',
} as const
